language: node_js
node_js:
- '12'
git:
  depth: 1
script:
- npm test
after_success:
- npm run build
deploy:
  provider: npm
  email: lmarianski@protonmail.com
  api_key:
    secure: ArjIpZ6zlgfG/HfnzYGqSWWYgZhRI0OF8JLz3khn713G2pO+eEz3acxqx68iaP/y3r7Ib/bGG6j5/dLpLPRj710lmWWcUnYl2yCK5/TdLyHDo7Qa7zuktB6BydDeay1oREp66RS6njyuY6dWjvgyrffrPKoA+vreYn4OLMe8k1Z1deOw7HQEgBF+w3dKqGJqcwRo2rKOh3kVmH+ETQhENW941VfOfvz+UH5f2PB8BeBj/Wm/KmGUji6KMOCI4WMghWcsTVFG/2sCnJjNqWWxDABxWVUWrXDVG+51uVORIMoQVOKXnmlsTF5cAEVpYPgMvfpOJa5YjGo0+R3K7Td81QUeWj8lzkftCuBAMVvXqiKxuBkm2pq82b59rUU/NKFyLJrRgglaw4lpzG7E4oFtge5wSEixUME6Q1ap8LRE4iWGaBfTh/hwD+uIVWoOI+dJtSyJ6OkcdvcpKXbuHr0Vg0rSfZ01QG06mPDl0gtA6bsmHkl3f2VN/atZhXs3zuo064T+YhEeqYm4pyM16/3qeWv1AjKkFKnv9gJo6tvKVDPUz1u/wneV8KwitaX/VHqVIbsVdZUNhQld4wOXGNpL7t/LcZ/7QPAEaq9WezmJoB0hK8lgGtwrawp6i86o9Lw82XR7vNIxEI7LU+4pRfioq8XAwh0hhkaLnI/gP1CsvVY=
  on:
    repo: lukas2005/fusebase-controlpanel
cache: npm
