language: node_js
node_js:
- '12'
git:
  depth: 1
script:
- npm test
after_success:
- npm run build
deploy:
  provider: npm
  email: lmarianski@protonmail.com
  api_key: $NPM_TOKEN
  on:
    repo: lukas2005/fusebase-controlpanel
  skip_cleanup: true
cache: npm
